"""`pcbkit new` — produce a project that is correct by construction.

Two things a human reliably gets wrong or skips: excluding generated output from
git (CR-005), and giving KiCad the fabricator's design rules instead of its own
defaults (CR-006). Both are produced here so neither depends on remembering.
"""

from __future__ import annotations

import datetime as _dt
import re
import tomllib
from pathlib import Path

from pcbkit import __version__
from pcbkit.core.result import Envelope, Finding, Severity
from pcbkit.profile import DEFAULT_PROFILE, Profile, ProfileError, load
from pcbkit.profile.dru import digest, render

PROJECT_FILE = "pcbkit.toml"

# Generated per CR-005: reproducible from the profile, so never committed.
GITIGNORE = """\
# Generated by pcbkit. Everything here is reproducible from what is committed,
# so committing it would make the repository large and the concerns muddy.
# See CR-005.
findings/
release/
build/
*.kicad_dru

# KiCad working files
*-backups/
*.kicad_prl
fp-info-cache
"""

_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")


def _starter_design(name: str) -> str:
    """A design file that builds immediately.

    An empty `src/` gives the user nothing to run, and the first thing they need
    is confirmation that the toolchain works end to end.
    """
    identifier = name.replace("-", "_")
    return f'''"""{name} — replace this with your circuit."""

from pcbkit.dsl import C, Gnd, Power, R, design, module, rule


@module
def blink(vcc, gnd):
    led = R("1k", pkg="0603")   # placeholder: swap for a real LED and resistor
    led(vcc, gnd)
    rule.decouple(led, max_mm=5)


@design("{identifier}", width_mm=30, height_mm=20, layers=2)
def {identifier}():
    vcc = Power("+3V3", 3.3)
    gnd = Gnd()
    blink(vcc, gnd)
'''


class ScaffoldError(RuntimeError):
    """The project could not be created."""


def _project_toml(name: str, profile: Profile, process_id: str) -> str:
    return f"""\
# pcbkit project. Committed; the generated files it describes are not.
name = "{name}"
created = "{_dt.date.today().isoformat()}"
pcbkit_version = "{__version__}"

[fabrication]
# The profile is copied into this project rather than referenced by name: a
# board revised in two years must regenerate the same rules, so its capability
# data travels with it. Same argument CR-004 makes for the toolchain.
profile = "{profile.vendor.lower()}"
process = "{process_id}"
"""


def new_project(
    directory: Path,
    *,
    name: str | None = None,
    profile_name: str = DEFAULT_PROFILE,
    layers: int = 2,
    process_id: str | None = None,
) -> Envelope:
    directory = Path(directory)
    name = name or directory.name

    if not _NAME_RE.match(name):
        return Envelope(
            command="new",
            ok=False,
            errors=[
                f"invalid project name {name!r}: must start with a letter and "
                "contain only letters, digits, hyphens, and underscores"
            ],
        )
    if directory.exists() and any(directory.iterdir()):
        return Envelope(
            command="new", ok=False, errors=[f"{directory} exists and is not empty"]
        )

    try:
        profile = load(profile_name)
        process = profile.process(process_id, layers=None if process_id else layers)
    except (ProfileError, KeyError) as exc:
        return Envelope(command="new", ok=False, errors=[str(exc)])

    (directory / "src").mkdir(parents=True, exist_ok=True)
    (directory / "src" / f"{name}.py").write_text(_starter_design(name))
    (directory / "profiles").mkdir(exist_ok=True)

    # Copied, not referenced: the comment in _project_toml explains why.
    (directory / "profiles" / f"{profile.vendor.lower()}.yaml").write_text(
        _profile_source_text(profile_name)
    )

    (directory / PROJECT_FILE).write_text(_project_toml(name, profile, process.id))
    (directory / ".gitignore").write_text(GITIGNORE)

    dru_text = render(profile, process)
    dru_path = directory / f"{name}.kicad_dru"
    dru_path.write_text(dru_text)

    findings: list[Finding] = []
    for gap in profile.unencoded_gaps():
        findings.append(
            Finding(
                source="profile",
                code=f"profile.gap.{gap.id}",
                severity=Severity.WARNING,
                message=f"{profile.vendor} limit not enforced by DRC: {' '.join(gap.why.split())}",
                fix="check this limit by hand before ordering, or extend the profile",
            )
        )

    return Envelope(
        command="new",
        data={
            "project": str(directory),
            "name": name,
            "profile": profile.provenance(),
            "process": process.id,
            "layers": process.layers,
            "design_rules": {
                "path": str(dru_path),
                "digest": digest(dru_text),
                "rules": dru_text.count("(rule "),
            },
            "created": sorted(
                str(p.relative_to(directory)) for p in directory.rglob("*") if p.is_file()
            ),
        },
        findings=findings,
    )


def _profile_source_text(profile_name: str) -> str:
    """Raw YAML of a built-in profile, so the copy keeps its comments."""
    from pcbkit.profile.loader import search_paths

    for directory in search_paths():
        candidate = directory / f"{profile_name}.yaml"
        if candidate.is_file():
            return candidate.read_text()
    raise ScaffoldError(f"cannot locate source text for profile {profile_name!r}")


def read_project(directory: Path) -> dict:
    path = Path(directory) / PROJECT_FILE
    if not path.is_file():
        raise ScaffoldError(f"{directory} is not a pcbkit project (no {PROJECT_FILE})")
    return tomllib.loads(path.read_text())


def check_design_rules(directory: Path) -> Envelope:
    """Regenerate the rules and compare, without overwriting.

    A silent overwrite would hide the two cases worth knowing about: someone
    edited the generated file, or the profile changed under it.
    """
    directory = Path(directory)
    try:
        config = read_project(directory)
        profile = load(config["fabrication"]["profile"], project=directory)
        process = profile.process(config["fabrication"]["process"])
    except (ScaffoldError, ProfileError, KeyError) as exc:
        return Envelope(command="profile check", ok=False, errors=[str(exc)])

    expected = render(profile, process)
    dru_path = directory / f"{config['name']}.kicad_dru"

    if not dru_path.is_file():
        return Envelope(
            command="profile check",
            data={"path": str(dru_path), "state": "missing"},
            findings=[
                Finding(
                    source="profile",
                    code="profile.dru_missing",
                    severity=Severity.ERROR,
                    message=f"{dru_path.name} does not exist",
                    fix="run `pcbkit profile regenerate`",
                )
            ],
        )

    actual = dru_path.read_text()
    if actual == expected:
        return Envelope(
            command="profile check",
            data={"path": str(dru_path), "state": "current", "digest": digest(actual)},
        )

    return Envelope(
        command="profile check",
        data={
            "path": str(dru_path),
            "state": "stale",
            "digest_on_disk": digest(actual),
            "digest_expected": digest(expected),
        },
        findings=[
            Finding(
                source="profile",
                code="profile.dru_stale",
                severity=Severity.ERROR,
                message=(
                    f"{dru_path.name} does not match the profile "
                    f"({digest(actual)} on disk, {digest(expected)} expected)"
                ),
                fix="run `pcbkit profile regenerate`, or revert the hand edit",
            )
        ],
    )


def regenerate_design_rules(directory: Path) -> Envelope:
    directory = Path(directory)
    try:
        config = read_project(directory)
        profile = load(config["fabrication"]["profile"], project=directory)
        process = profile.process(config["fabrication"]["process"])
    except (ScaffoldError, ProfileError, KeyError) as exc:
        return Envelope(command="profile regenerate", ok=False, errors=[str(exc)])

    text = render(profile, process)
    path = directory / f"{config['name']}.kicad_dru"
    path.write_text(text)
    return Envelope(
        command="profile regenerate",
        data={"path": str(path), "digest": digest(text), "rules": text.count("(rule ")},
    )
