"""`pcbkit new` — produce a project that is correct by construction.

Two things a human reliably gets wrong or skips: excluding generated output from
git (CR-005), and giving KiCad the fabricator's design rules instead of its own
defaults (CR-006). Both are produced here so neither depends on remembering.
"""

from __future__ import annotations

import datetime as _dt
import re
import tomllib
from pathlib import Path
from typing import NamedTuple

from pcbkit import __version__
from pcbkit.core.kicad import CONFIRMED_KICAD_VERSION
from pcbkit.core.result import Envelope, Finding, Severity
from pcbkit.profile import DEFAULT_PROFILE, Profile, ProfileError, load
from pcbkit.profile.dru import digest, render

PROJECT_FILE = "pcbkit.toml"

# Generated per CR-005: reproducible from the profile, so never committed.
GITIGNORE = """\
# Generated by pcbkit. Everything here is reproducible from what is committed,
# so committing it would make the repository large and the concerns muddy.
# See CR-005.
findings/
release/
build/
*.kicad_dru

# KiCad working files
*-backups/
*.kicad_prl
fp-info-cache
"""

# CR-008: a board change reaches the default branch only through a reviewed
# pull request whose checks passed. The two required status contexts.
REQUIRED_CONTEXTS = ("gate", "agent-review")

# The generated workflow needs KiCad 10 and the pcbnew module, neither of which
# is on a hosted runner image. Pinned to the version pcbkit's format numbers
# were confirmed against, for the reason CR-004 gives: an unpinned toolchain
# produces output that differs between machines and nobody notices until it
# matters.
#
# The tag was confirmed to exist on the registry on 2026-08-29. A generated
# workflow whose container does not resolve is a gate that cannot pass, which
# is the same failure as naming a verb that does not exist -- so re-confirm it
# when CONFIRMED_KICAD_VERSION moves.
KICAD_IMAGE = f"kicad/kicad:{CONFIRMED_KICAD_VERSION}"

# pcbkit is not on a package index yet, so a generated project fetches it from
# source.
#
# The default ref is the default branch, which resolves. Pinning to
# `v{__version__}` would be better for the reason CR-004 gives -- an unpinned
# toolchain gives a board whose CI result can change without the board
# changing -- but pcbkit publishes no tags yet, so that ref does not exist and
# every generated project's first CI run would die before pcbkit was installed.
# A gate that cannot pass is the same failure as one that cannot fail; it is
# the reason KICAD_IMAGE was checked against the registry above.
#
# `pcbkit new --pcbkit-ref <tag-or-commit>` pins it, and the generated README
# says to, so the honest default is the one that runs and the pinned one is a
# flag away rather than a broken file away.
PCBKIT_REPO = "https://github.com/BIOS9/agentic_pcb_toolkit"
DEFAULT_PCBKIT_REF = "main"


def pcbkit_source(ref: str = DEFAULT_PCBKIT_REF) -> str:
    return f"git+{PCBKIT_REPO}@{ref}"


def _runner(ref: str) -> str:
    return f"uvx --from {pcbkit_source(ref)}"

# CR-008's escape hatch, shared verbatim between this repository's own workflow
# and every generated one -- `tests/test_scaffold.py` fails if the two copies
# drift.
#
# A check may be knowingly red because the work is staged rather than broken:
# the schematic gains a connector, the layout follows later, and DRC fails in
# between. Blocking that is wrong and bypassing it quietly is worse, so the
# deferral is declared in the pull request body and is machine-readable:
#
#     deferred: checks
#     why: schematic adds the USB-C connector; layout lands in #42
#     resolves: #42
#
# Three lines, because each carries information a bare override label does not:
# which check, why, and what clears it.
GATE_JOB = """\
  # `checks` is deliberately *not* the required status context: a required
  # context in GitHub is all-or-nothing, so a knowingly-red check could only be
  # got past by an admin bypass -- the quiet override CR-008 rejects. `gate` is
  # required instead, and it passes either because `checks` is green or because
  # the pull request body declares the failure, says why, and names what
  # resolves it.
  gate:
    needs: [checks]
    if: always() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Require a green check, or a declared deferral
        env:
          RESULT: ${{ needs.checks.result }}
          BODY: ${{ github.event.pull_request.body }}
        run: |
          set -uo pipefail

          if [ "$RESULT" = "success" ]; then
            echo "checks passed"
            exit 0
          fi

          verdict=$(printf '%s\\n' "$BODY" | tr -d '\\r' | awk -v want=checks '
            # A declaration is prose at column 0, not an example. Fenced blocks and HTML
            # comments both put text at column 0, and this syntax appears inside both in
            # the documentation that teaches it -- so a pull request quoting its own
            # README would otherwise defer its own checks, and one hiding the block in a
            # comment would defer them with nothing visible on the page.
            #
            # The fence is matched by delimiter and run length, not toggled: quoting a
            # document that itself contains a fence needs a longer outer fence, and a
            # parity toggle would treat the inner one as a close and read the quoted
            # example as a live declaration.
            match($0, /^[[:space:]]*(```+|~~~+)/) {
              run = substr($0, RSTART, RLENGTH); sub(/^[[:space:]]*/, "", run)
              ch = substr(run, 1, 1)
              if (!fence) { fence = 1; fence_ch = ch; fence_len = length(run) }
              else if (ch == fence_ch && length(run) >= fence_len) { fence = 0 }
              next
            }
            fence { next }
            /<!--/ { comment = 1 }
            comment { if (/-->/) comment = 0; next }

            function judge() {
              if (name == want && why != "" && res ~ /^#?[1-9][0-9]*$/) return "declared"
              if (name == want) return "malformed"
              return ""
            }

            # Evaluated when a block ends rather than on a fixed field order, so
            # `resolves:` before `why:` is the same declaration, and a block immediately
            # followed by another is not lost.
            /^deferred:/ {
              if ((verdict = judge()) != "") exit
              sub(/^deferred:[[:space:]]*/, ""); gsub(/[[:space:]]+$/, "")
              name = $0; why = ""; res = ""; next
            }
            /^why:/ {
              if (name != "") { sub(/^why:[[:space:]]*/, ""); gsub(/[[:space:]]+$/, ""); why = $0 }
              next
            }
            /^resolves:/ {
              if (name != "") { sub(/^resolves:[[:space:]]*/, ""); gsub(/[[:space:]]+$/, ""); res = $0 }
              next
            }
            END { if (verdict == "") verdict = judge(); if (verdict != "") print verdict }
          ')

          case "$verdict" in
            declared)
              echo "::warning::checks is '$RESULT' and deferred by declaration in the pull request body"
              echo "Tracked debt, not a pass. An unresolved deferral is a finding at the fab gate."
              exit 0 ;;
            malformed)
              echo "::error::the deferral for 'checks' is incomplete"
              echo "::error::it needs all three lines: 'deferred: checks', a non-empty 'why:', and 'resolves: #<issue>'"
              echo "::error::order does not matter; a block inside a code fence or an HTML comment does not count"
              exit 1 ;;
            *)
              echo "::error::checks is '$RESULT' and no deferral declares it"
              echo "::error::fix the check, or declare the deferral in the pull request body:"
              echo "::error::  deferred: checks"
              echo "::error::  why: <what is staged, and why this is not broken>"
              echo "::error::  resolves: #<issue that clears it>"
              echo "::error::at the start of a line, not inside a code fence or an HTML comment"
              echo "::error::an unclosed fence or '<!--' earlier in the body hides everything after it"
              exit 1 ;;
          esac
"""

# Every command the generated workflow runs, as data rather than as a YAML
# blob, so a test can assert each one is a verb the CLI actually has. The
# defect CR-008 was raised over was a CI step that could not fail; a step that
# cannot even run is the same failure one stage earlier.
#
# `{design}` expands to the starter design file. `gates` says whether the step
# can fail on a bad board, as opposed to only on a broken tool -- recorded per
# step rather than inferred from the command, because inferring it is how a
# test comes to assert its own comment.
class Step(NamedTuple):
    label: str
    command: str
    gates: bool


CHECK_STEPS: tuple[Step, ...] = (
    # Setup, not a gate: it fails only if the toolchain itself is broken.
    Step("Toolchain", "pcbkit doctor --strict", gates=False),
    # Also setup. The rules file is generated and gitignored (CR-005), so CI
    # makes its own from the committed profile rather than trusting one in the
    # tree. It exits 0 for any well-formed project.
    Step("Design rules from the profile", "pcbkit profile regenerate .", gates=False),
    # The gate. `--strict` turns error-severity findings into a nonzero exit,
    # so a design with an unconnected part, a duplicate refdes, or a dangling
    # reference fails CI. It is the structural layer only: ERC, profile DRC,
    # and the electrical rules join it as `pcbkit check --strict` at M7, and
    # naming that verb before it exists would emit a workflow that cannot run.
    Step("Build", "pcbkit build {design} --strict", gates=True),
)


def _workflow(name: str, ref: str) -> str:
    """The checks workflow for a generated project.

    Deliberately not a copy of this repository's own workflow, which runs
    through a Nix flake a board project does not have. Two things it must get
    right or it emits a gate that cannot pass:

    * KiCad 10 and its `pcbnew` module are not on the hosted runner image, so
      the job runs inside the fabricator-independent KiCad container.
    * pcbkit is not published, so it is fetched from source at the version that
      generated this project. Pinned, for the same reason the profile is copied
      rather than referenced.
    """
    steps = "\n".join(
        f"      - name: {step.label}\n        run: {_runner(ref)} {step.command.format(design=f'src/{name}.py')}"
        for step in CHECK_STEPS
    )
    return f"""\
name: checks

# Generated by `pcbkit new`. Every verb exits 0 with findings and nonzero only
# when a tool failed, so --strict is what turns a check into a gate.
#
# The container carries KiCad and pcbnew; uvx supplies pcbkit itself. Bump the
# tag when you upgrade KiCad, and re-run the build before trusting the output:
# a format-version change is a real difference, not noise.

on:
  push:
    branches: [main]
  pull_request:
    # `edited` matters: a deferral is declared in the pull request body, so
    # editing the body must re-evaluate the gate.
    types: [opened, synchronize, reopened, edited]

# `gate` reads the pull request body as it was when the event fired, so two
# edits in quick succession race and the run that finishes last wins.
# Superseding the older run makes the newest body the one that decides.
concurrency:
  group: checks-${{{{ github.event.pull_request.number || github.ref }}}}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    container: {KICAD_IMAGE}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

{steps}

{GATE_JOB}"""


def _wrap(text: str) -> str:
    """Hard-wrap to match the rest of the generated README."""
    import textwrap

    return "\n".join(textwrap.wrap(text, width=79))


def _readme(name: str, profile: Profile, process_id: str, ref: str) -> str:
    """What the project is, how to check it, and what to enable by hand.

    pcbkit cannot configure another account's repository, so the settings are
    stated rather than pretended (CR-008).
    """
    commands = "\n".join(
        f"$ {step.command.format(design=f'src/{name}.py')}" for step in CHECK_STEPS
    )
    contexts = "\n".join(f"   - `{context}`" for context in REQUIRED_CONTEXTS)

    # A 40-character hash or a version tag is a pin; anything else is a moving
    # ref, and the difference is the whole of CR-004 for this project.
    pinned = bool(re.fullmatch(r"[0-9a-f]{40}|v[0-9].*", ref))
    if pinned:
        ref_note = _wrap(
            f"pcbkit itself is pinned at `{ref}`, so this project's CI result "
            "changes only when the project does."
        )
    else:
        ref_note = (
            _wrap(
                f"pcbkit itself is fetched from `{ref}`, which is a moving "
                "ref: this project's CI result can change without the project "
                "changing, because a pcbkit release alters the output and "
                "nothing here records that it did. Pin it to a tag or a commit "
                "once you have one you trust, either with"
            )
            + "\n\n```console\n$ pcbkit new <project> --pcbkit-ref <tag-or-commit>\n```\n\n"
            + _wrap("or by editing the `uvx --from` ref in the workflow directly.")
        )
    return f"""\
# {name}

A pcbkit board project. The circuit is Python under `src/`; everything KiCad
reads is generated from it.

```console
{commands}
```

## What is committed, and what is not

`pcbkit.toml`, `profiles/{profile.vendor.lower()}.yaml`, and `src/` are the
project. Gerbers, renders, findings, and `{name}.kicad_dru` are generated from
those, and `.gitignore` excludes them — regenerate them, never commit them.

The fabricator profile is *copied* into this project rather than referenced by
name, so a board revised in two years regenerates the same design rules.

Fabricator: {profile.vendor}, process `{process_id}`.

## Before you order

`pcbkit doctor --strict` reports whether the toolchain is pinned. An unpinned
build works; it is just not guaranteed to match another machine.

## Continuous integration

`.github/workflows/checks.yml` runs the same commands on every pull request,
inside `{KICAD_IMAGE}` because KiCad 10 and its `pcbnew` module are not on a
hosted runner image.

{ref_note}

Whatever you choose, it must be a ref that resolves: a workflow whose first step
cannot install pcbkit is a gate that can never pass, and `gate` is the context
you are about to require.

## Branch protection

The workflow only reports — it does not block. Enabling that is an
account-level change pcbkit cannot make for you.

Requiring a context that nothing produces blocks every merge, so read this
before you select any: `gate` is produced by the generated workflow, and
`agent-review` is produced **only if you add a review workflow of your own**.
If you are not running one, leave `agent-review` out of step 3.

Require `gate` rather than `checks` — see the next section for why.

On `main`, in Settings → Branches → Add branch protection rule:

1. Require a pull request before merging.
2. Require status checks to pass, and require branches to be up to date.
3. Select these contexts:
{contexts}

## Deferring a check, without bypassing it

A check is sometimes knowingly red because the work is staged, not broken: the
schematic gains a connector and the layout follows in a later change, so DRC
fails in between. Blocking that is wrong; bypassing it quietly is worse.

A required status context is all-or-nothing, so `gate` is the required one and
`checks` is not. `gate` passes when `checks` is green, or when the pull request
body declares the failure:

```
deferred: checks
why: schematic adds the USB-C connector; layout lands in #42
resolves: #42
```

Three lines, because each carries something a bare override label does not:
which check, why, and what clears it. All three are required — an incomplete
declaration fails the gate rather than passing it. Their order does not matter.

Each must start at the beginning of a line, and **a block inside a code fence
or an HTML comment does not count**. Otherwise a pull request that quoted this
README would defer its own checks, and one that hid the block in a comment
would defer them with nothing visible on the page — which is the quiet override
the three lines exist to prevent.

A deferral is tracked debt, not a pass. It stays visible in the pull request
list, and a board that reaches an order with one unresolved is a board whose
checks nobody finished.

An unreviewed board change becomes an unreviewed order, which is the point at
which a mistake starts costing money.
"""


_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")

# The ref is interpolated into a `run:` line of the generated workflow, so it
# has to be a ref and not a command. A conservative subset of what git accepts:
# anything outside it either is not a valid ref anyway or would turn a workflow
# step into something its reader did not write.
_REF_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]*$")


def valid_ref(ref: str) -> bool:
    return bool(_REF_RE.match(ref)) and ".." not in ref and not ref.endswith(".lock")


def _starter_design(name: str) -> str:
    """A design file that builds immediately.

    An empty `src/` gives the user nothing to run, and the first thing they need
    is confirmation that the toolchain works end to end.
    """
    identifier = name.replace("-", "_")
    return f'''"""{name} — replace this with your circuit."""

from pcbkit.dsl import C, Gnd, Power, R, design, module, rule


@module
def blink(vcc, gnd):
    led = R("1k", pkg="0603")   # placeholder: swap for a real LED and resistor
    led(vcc, gnd)
    rule.decouple(led, max_mm=5)


@design("{identifier}", width_mm=30, height_mm=20, layers=2)
def {identifier}():
    vcc = Power("+3V3", 3.3)
    gnd = Gnd()
    blink(vcc, gnd)
'''


class ScaffoldError(RuntimeError):
    """The project could not be created."""


def _project_toml(name: str, profile: Profile, process_id: str) -> str:
    return f"""\
# pcbkit project. Committed; the generated files it describes are not.
name = "{name}"
created = "{_dt.date.today().isoformat()}"
pcbkit_version = "{__version__}"

[fabrication]
# The profile is copied into this project rather than referenced by name: a
# board revised in two years must regenerate the same rules, so its capability
# data travels with it. Same argument CR-004 makes for the toolchain.
profile = "{profile.vendor.lower()}"
process = "{process_id}"
"""


def new_project(
    directory: Path,
    *,
    name: str | None = None,
    profile_name: str = DEFAULT_PROFILE,
    layers: int = 2,
    process_id: str | None = None,
    pcbkit_ref: str = DEFAULT_PCBKIT_REF,
) -> Envelope:
    directory = Path(directory)
    name = name or directory.name

    if not _NAME_RE.match(name):
        return Envelope(
            command="new",
            ok=False,
            errors=[
                f"invalid project name {name!r}: must start with a letter and "
                "contain only letters, digits, hyphens, and underscores"
            ],
        )
    if not valid_ref(pcbkit_ref):
        return Envelope(
            command="new",
            ok=False,
            errors=[
                f"invalid pcbkit ref {pcbkit_ref!r}: must be a git ref -- "
                "letters, digits, and '._/-' only. It is written into a "
                "workflow step, so anything else would put text there that "
                "nobody wrote as a command."
            ],
        )
    if directory.exists() and any(directory.iterdir()):
        return Envelope(
            command="new", ok=False, errors=[f"{directory} exists and is not empty"]
        )

    try:
        profile = load(profile_name)
        process = profile.process(process_id, layers=None if process_id else layers)
    except (ProfileError, KeyError) as exc:
        return Envelope(command="new", ok=False, errors=[str(exc)])

    (directory / "src").mkdir(parents=True, exist_ok=True)
    (directory / "src" / f"{name}.py").write_text(_starter_design(name))
    (directory / "profiles").mkdir(exist_ok=True)

    # Copied, not referenced: the comment in _project_toml explains why.
    (directory / "profiles" / f"{profile.vendor.lower()}.yaml").write_text(
        _profile_source_text(profile_name)
    )

    (directory / PROJECT_FILE).write_text(_project_toml(name, profile, process.id))
    (directory / ".gitignore").write_text(GITIGNORE)
    (directory / "README.md").write_text(_readme(name, profile, process.id, pcbkit_ref))

    # CR-008: the workflow ships with the project, the branch protection it
    # feeds is documented in the README because pcbkit cannot enable it.
    workflows = directory / ".github" / "workflows"
    workflows.mkdir(parents=True, exist_ok=True)
    (workflows / "checks.yml").write_text(_workflow(name, pcbkit_ref))

    dru_text = render(profile, process)
    dru_path = directory / f"{name}.kicad_dru"
    dru_path.write_text(dru_text)

    findings: list[Finding] = []
    for gap in profile.unencoded_gaps():
        findings.append(
            Finding(
                source="profile",
                code=f"profile.gap.{gap.id}",
                severity=Severity.WARNING,
                message=f"{profile.vendor} limit not enforced by DRC: {' '.join(gap.why.split())}",
                fix="check this limit by hand before ordering, or extend the profile",
            )
        )

    return Envelope(
        command="new",
        data={
            "project": str(directory),
            "name": name,
            "profile": profile.provenance(),
            "process": process.id,
            "layers": process.layers,
            "design_rules": {
                "path": str(dru_path),
                "digest": digest(dru_text),
                "rules": dru_text.count("(rule "),
            },
            "created": sorted(
                str(p.relative_to(directory)) for p in directory.rglob("*") if p.is_file()
            ),
        },
        findings=findings,
    )


def _profile_source_text(profile_name: str) -> str:
    """Raw YAML of a built-in profile, so the copy keeps its comments."""
    from pcbkit.profile.loader import search_paths

    for directory in search_paths():
        candidate = directory / f"{profile_name}.yaml"
        if candidate.is_file():
            return candidate.read_text()
    raise ScaffoldError(f"cannot locate source text for profile {profile_name!r}")


def read_project(directory: Path) -> dict:
    path = Path(directory) / PROJECT_FILE
    if not path.is_file():
        raise ScaffoldError(f"{directory} is not a pcbkit project (no {PROJECT_FILE})")
    return tomllib.loads(path.read_text())


def check_design_rules(directory: Path) -> Envelope:
    """Regenerate the rules and compare, without overwriting.

    A silent overwrite would hide the two cases worth knowing about: someone
    edited the generated file, or the profile changed under it.
    """
    directory = Path(directory)
    try:
        config = read_project(directory)
        profile = load(config["fabrication"]["profile"], project=directory)
        process = profile.process(config["fabrication"]["process"])
    except (ScaffoldError, ProfileError, KeyError) as exc:
        return Envelope(command="profile check", ok=False, errors=[str(exc)])

    expected = render(profile, process)
    dru_path = directory / f"{config['name']}.kicad_dru"

    if not dru_path.is_file():
        return Envelope(
            command="profile check",
            data={"path": str(dru_path), "state": "missing"},
            findings=[
                Finding(
                    source="profile",
                    code="profile.dru_missing",
                    severity=Severity.ERROR,
                    message=f"{dru_path.name} does not exist",
                    fix="run `pcbkit profile regenerate`",
                )
            ],
        )

    actual = dru_path.read_text()
    if actual == expected:
        return Envelope(
            command="profile check",
            data={"path": str(dru_path), "state": "current", "digest": digest(actual)},
        )

    return Envelope(
        command="profile check",
        data={
            "path": str(dru_path),
            "state": "stale",
            "digest_on_disk": digest(actual),
            "digest_expected": digest(expected),
        },
        findings=[
            Finding(
                source="profile",
                code="profile.dru_stale",
                severity=Severity.ERROR,
                message=(
                    f"{dru_path.name} does not match the profile "
                    f"({digest(actual)} on disk, {digest(expected)} expected)"
                ),
                fix="run `pcbkit profile regenerate`, or revert the hand edit",
            )
        ],
    )


def regenerate_design_rules(directory: Path) -> Envelope:
    directory = Path(directory)
    try:
        config = read_project(directory)
        profile = load(config["fabrication"]["profile"], project=directory)
        process = profile.process(config["fabrication"]["process"])
    except (ScaffoldError, ProfileError, KeyError) as exc:
        return Envelope(command="profile regenerate", ok=False, errors=[str(exc)])

    text = render(profile, process)
    path = directory / f"{config['name']}.kicad_dru"
    path.write_text(text)
    return Envelope(
        command="profile regenerate",
        data={"path": str(path), "digest": digest(text), "rules": text.count("(rule ")},
    )
