"""Fabricator profiles: data in, KiCad design rules out (CR-006)."""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from pcbkit.profile import ProfileError, available, load
from pcbkit.profile.dru import digest, render, rules_for

REPO = Path(__file__).resolve().parent.parent


def test_the_default_profile_loads_and_declares_provenance():
    profile = load("jlcpcb")
    assert profile.vendor == "JLCPCB"
    assert profile.source.startswith("https://")
    # A profile without a date is a profile nobody can judge the staleness of.
    assert profile.retrieved.year >= 2026
    assert profile.derived_from


def test_limits_are_keyed_by_process_not_flat():
    """Outer and inner copper already disagree at two layers."""
    limits = load("jlcpcb").process(layers=2).limits
    assert limits.track_width_mm.outer != limits.track_width_mm.inner
    assert limits.track_width_mm.for_layer("outer") == 0.127
    assert limits.track_width_mm.for_layer("inner") == 0.09


def test_gaps_are_tracked_rather_than_silent():
    """The rule set this was derived from lost three limits to TODO comments."""
    gaps = load("jlcpcb").unencoded_gaps()
    assert {g.id for g in gaps} >= {"npth_pad_margin", "hole_to_edge"}
    assert all(g.why for g in gaps)


def test_unknown_profile_names_what_is_available():
    with pytest.raises(ProfileError, match="available:"):
        load("no-such-fab")


def test_unknown_process_is_an_error_not_a_default():
    """Silently falling back to another stackup would produce wrong rules."""
    profile = load("jlcpcb")
    with pytest.raises(KeyError, match="no process"):
        profile.process("6layer-2oz")
    with pytest.raises(KeyError, match="no process for 6 layers"):
        profile.process(layers=6)


def test_typo_in_a_limit_name_is_rejected(tmp_path):
    """A rule that never fires looks identical to one that always passes."""
    bad = tmp_path / "bad.yaml"
    bad.write_text(
        "vendor: X\nsource: https://x\nretrieved: 2026-01-01\n"
        "processes:\n  - id: p\n    layers: 2\n    copper_oz: 1.0\n"
        "    limits:\n      track_widht_mm: {outer: 0.1, inner: 0.1}\n"
    )
    with pytest.raises(ProfileError):
        load(bad)


def test_generated_rules_carry_provenance_and_declare_gaps():
    profile = load("jlcpcb")
    text = render(profile, profile.process(layers=2))
    assert "GENERATED by pcbkit" in text
    assert profile.retrieved.isoformat() in text
    assert profile.source in text
    # The header must say what DRC will not catch, or a clean run misleads.
    assert "are NOT enforced" in text
    assert "npth_pad_margin" in text


def test_generation_is_deterministic():
    """`profile check` reports real drift only if regeneration is stable."""
    profile = load("jlcpcb")
    process = profile.process(layers=2)
    assert digest(render(profile, process)) == digest(render(profile, process))


def test_every_rule_has_a_constraint():
    for rule in rules_for(load("jlcpcb").process(layers=2)):
        assert rule.constraints, rule.name


def test_limit_values_never_appear_in_python_source():
    """AGENTS.md rule 10: a limit in code is a board built wrong.

    Checks the distinctive values -- the ones that could only have come from
    the profile, not from ordinary arithmetic.
    """
    limits = load("jlcpcb").process(layers=2).limits.model_dump()

    def numbers(value):
        if isinstance(value, (int, float)):
            yield float(value)
        elif isinstance(value, dict):
            for v in value.values():
                yield from numbers(v)

    distinctive = {
        n for n in numbers(limits)
        if len(f"{n:g}".split(".")[-1]) >= 3  # 0.127, 0.075, 0.254 -- not 0.2 or 1.0
    }
    assert distinctive, "expected some distinctive limit values to guard"

    offenders = []
    for path in (REPO / "pcbkit").rglob("*.py"):
        if "__pycache__" in path.parts:
            continue
        text = path.read_text()
        for value in distinctive:
            if re.search(rf"(?<![\d.]){value:g}(?![\d])", text):
                offenders.append(f"{path.relative_to(REPO)}: {value:g}")
    assert not offenders, "fabricator limits hardcoded in Python:\n" + "\n".join(offenders)
